### ISSUE TITLE
_BECompiler() not handling exception prevents engine from starting

### ISSUE THREAD

**Issue by xhoms** [PaloAltoNetworks/minemeld-core#234]
By error I created a prototype with the condition '<expression> == None' instead of '<expression == null'.

_BECompiler fails to set the object's 'value' attribute and that will create an unhandled exception in the return statement of the Condition() method.

The engine won't start

`line 1:15 mismatched input 'None' expecting {'true', 'false', 'null', STRING, NUMBER}
2017-07-15T03:43:04 (16672)launcher._run_chassis ERROR: Exception in chassis main procedure
Traceback (most recent call last):
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/run/launcher.py", line 53, in _run_chassis
    c.configure(fts)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/chassis.py", line 102, in configure
    config=ftconfig.get('config', {})
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/__init__.py", line 10, in factory
    config=config
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/redis.py", line 35, in __init__
    super(RedisSet, self).__init__(name, chassis, config)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/actorbase.py", line 17, in __init__
    super(ActorBaseFT, self).__init__(*args, **kwargs)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 198, in __init__
    self.configure()
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/redis.py", line 38, in configure
    super(RedisSet, self).configure()
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 341, in configure
    self.infilters = _Filters(self.config.get('infilters', []))
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 57, in __init__
    cf['conditions'].append(condition.Condition(c))
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/condition/interface.py", line 62, in __init__
    self.expression, self.comparator, self.value = self._parse_boolexpr(s)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/condition/interface.py", line 76, in _parse_boolexpr
    return eb.expression, eb.comparator, eb.value
AttributeError: '_BECompiler' object has no attribute 'value'
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/run/launcher.py", line 53, in _run_chassis
    c.configure(fts)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/chassis.py", line 102, in configure
    config=ftconfig.get('config', {})
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/__init__.py", line 10, in factory
    config=config
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/redis.py", line 35, in __init__
    super(RedisSet, self).__init__(name, chassis, config)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/actorbase.py", line 17, in __init__
    super(ActorBaseFT, self).__init__(*args, **kwargs)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 198, in __init__
    self.configure()
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/redis.py", line 38, in configure
    super(RedisSet, self).configure()
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 341, in configure
    self.infilters = _Filters(self.config.get('infilters', []))
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 57, in __init__
    cf['conditions'].append(condition.Condition(c))
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/condition/interface.py", line 62, in __init__
    self.expression, self.comparator, self.value = self._parse_boolexpr(s)
  File "/opt/minemeld/engine/0.9.38.post1/local/lib/python2.7/site-packages/minemeld/ft/condition/interface.py", line 76, in _parse_boolexpr
    return eb.expression, eb.comparator, eb.value
AttributeError: '_BECompiler' object has no attribute 'value'
`

**Comment by jtschichold** [comment]
What do you think should be the correct behavior ?

**Comment by xhoms** [comment]
I suggest `_parse_boolexpr()`  in class `Condition` to check the None condition of class attributes that should be set by `_BECompiler()` and replace them by default values.

A better solution would be to implement a syntax checker in Boolean Expresions provided by the user in configuration files and reject such a configuration files.
