### ISSUE TITLE
Add check for unicode in TAXII Miner

### ISSUE THREAD

**Issue by jtschichold** [PaloAltoNetworks/minemeld-core#275]
```
2018-04-18T16:24:22 (4743)basepoller._polling_loop INFO: Polling PNFP-FSISAC-3
2018-04-18T16:24:24 (4743)taxii._check_collections INFO: PNFP-FSISAC-3 - message binding: ['urn:taxii.mitre.org:message:xml:1.1']
2018-04-18T16:24:24 (4743)taxii._check_collections INFO: PNFP-FSISAC-3 - poll service found
2018-04-18T16:24:24 (4743)taxii._incremental_poll_collection INFO: PNFP-FSISAC-3 - polling datetime.datetime(2018, 3, 20, 11, 12$
2018-04-18T16:24:25 (4743)taxii._handle_content_blocks ERROR: PNFP-FSISAC-3 - exception in _handle_content_blocks
Traceback (most recent call last):
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 539, in _handle_content_blocks
   co = self._decode_observable(o)
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 595, in _decode_observable
   return self._decode_object_properties(op, odict=odict)
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 763, in _decode_object_propert$
   ov = ov.get('value', None)
AttributeError: 'unicode' object has no attribute 'get'
2018-04-18T16:24:25 (4743)basepoller._poll ERROR: Exception in polling loop for PNFP-FSISAC-3: 'unicode' object has no attribute$
Traceback (most recent call last):
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/basepoller.py", line 721, in _poll
   performed = self._polling_loop()
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/basepoller.py", line 597, in _polling_loop
   for nitem, item in enumerate(iterator):
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 470, in _incremental_poll_coll$
   end=cend
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 414, in _poll_collection
   stix_objects
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 539, in _handle_content_blocks
   co = self._decode_observable(o)
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 595, in _decode_observable
   return self._decode_object_properties(op, odict=odict)
 File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 763, in _decode_object_propert$
   ov = ov.get('value', None)
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by jtschichold** [comment]
This should have been fixed with #278, let's wait for validation.
