### ISSUE TITLE
Mine Meld Core crash - 'launcher.main ERROR: Exception initializing graph'

### ISSUE THREAD

**Issue by simonsigre** [PaloAltoNetworks/minemeld-core#313]
The following item seemed to have caused the service to fail
```
2019-01-24T10:00:32 (1012)launcher.main INFO: multiprocessing: #cores: 1
2019-01-24T10:00:32 (1012)launcher.main INFO: multiprocessing: max #chassis: 1
2019-01-24T10:00:32 (1012)launcher.main INFO: Number of chassis: 1
2019-01-24T10:00:32 (1016)loader.load INFO: Loading minemeld_nodes:minemeld.ft.taxii.TaxiiClient
2019-01-24T10:00:32 (1012)launcher.main ERROR: Exception initializing graph
Traceback (most recent call last):
  File "/opt/minemeld/engine/core/minemeld/run/launcher.py", line 283, in main
    mbusmaster.start()
  File "/opt/minemeld/engine/core/minemeld/mgmtbus.py", line 461, in start
    self.comm.start()
  File "/opt/minemeld/engine/core/minemeld/comm/amqp.py", line 595, in start
    c = amqp.connection.Connection(**self.amqp_config)
  File "/opt/minemeld/engine/current/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/opt/minemeld/engine/current/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/opt/minemeld/engine/current/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/opt/minemeld/engine/current/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
2019-01-24T10:00:32 (1012)mgmtbus.checkpoint_graph INFO: checkpoint_graph called, checking current state
2019-01-24T10:00:32 (1012)mgmtbus.checkpoint_graph INFO: graph status None, checkpoint_graph ignored
Traceback (most recent call last):
  File "/opt/minemeld/engine/current/bin/mm-run", line 11, in <module>
    load_entry_point('minemeld-core', 'console_scripts', 'mm-run')()
  File "/opt/minemeld/engine/core/minemeld/run/launcher.py", line 283, in main
    mbusmaster.start()
  File "/opt/minemeld/engine/core/minemeld/mgmtbus.py", line 461, in start
    self.comm.start()
  File "/opt/minemeld/engine/core/minemeld/comm/amqp.py", line 595, in start
    c = amqp.connection.Connection(**self.amqp_config)
  File "/opt/minemeld/engine/current/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/opt/minemeld/engine/current/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/opt/minemeld/engine/current/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/opt/minemeld/engine/current/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
socket.error: [Errno 111] Connection refused
```

**Comment by jtschichold** [comment]
Hi @simonsigre,
is this based on CentOS? I am working on simplifying MineMeld with a new pubsub mechanism based on Redis and avoid RabbitMQ.
Check the branch `rel-0.9.60` and let me know if you are interested in testing it.

**Comment by simonsigre** [comment]
This was on a clean Ubuntu Server install
`VERSION="16.04.5 LTS (Xenial Xerus)"`
.. Will have a look at `rel-0.9.60` and should be able to stand this up next to existing ones to provide exact comparison.

**Comment by jtschichold** [comment]
My fault, I assumed it was CentOS 7. The error is an issue with RabbitMQ on the OS not accepting requests. Could you check if RabbitMQ service is up and running? If you have installed via Ansible it's worth rebooting the instance after the installation (if you haven't done that already) to make sure all the services are properly started.

If you want to try the 0.9.60, you should:
- use the `rel-0.9.60` branch of Ansible (`git clone -b rel-0.9.60 https://github.com/PaloAltoNetworks/minemeld-ansible.git`)
- change the `local.yml` file in the playbook to point to the rel-0.9.60 branch for the core: `minemeld_core_version: rel-0.9.60`
- run the playbook as usual

**Comment by simonsigre** [comment]
`Could you check if RabbitMQ service is up and running?` - Yes that's all fine and working
` If you have installed via Ansible it's worth rebooting the instance after the installation (if you haven't done that already)` - Yes its been rebooted a few times

I have a watchdog script running now and it hasn't skipped a beat in weeks... I might hold off on swapping branches as this is very much production for us.
