### ISSUE TITLE
cif.py - updated arrow.py depreciated plural use for replace, should now use shift

### ISSUE THREAD

**Issue by erush6861** [PaloAltoNetworks/minemeld-core#346]
2019-08-20T22:45:58 (20065)basepoller._polling_loop INFO: Polling cif_Feed-1566362939368-1566363119009
2019-08-20T22:45:58 (20065)basepoller._poll ERROR: Exception in polling loop for cif_Feed-1566362939368-1566363119009: unknown attribute: "days"
Traceback (most recent call last):
  File "/opt/minemeld/engine/core/minemeld/ft/basepoller.py", line 729, in _poll
    performed = self._polling_loop()
  File "/opt/minemeld/engine/core/minemeld/ft/basepoller.py", line 576, in _polling_loop
    iterator = self._build_iterator(now)
  File "/opt/minemeld/engine/core/minemeld/ft/cif.py", line 139, in _build_iterator
    now.replace(hours=-168).format('YYYY-MM-DDTHH:mm:ss')
  File "/opt/minemeld/engine/current/lib/python2.7/site-packages/arrow/arrow.py", line 590, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "days"

https://github.com/crsmithdev/arrow/commit/976b6ea3554185d20e084a1d5b2e3c7294946e63
"replace() with plural property to shift value is deprecated, use shift() instead"

line 139:
now.**replace**(days=-days).format('YYYY-MM-DDTHH:mm:ss')

change to:
now.**shift**(days=-days).format('YYYY-MM-DDTHH:mm:ss')

**Comment by JesseBowling** [comment]
#350 Should solve this issue....

**Comment by ckrez** [comment]
Try this quick workaround in the meantime:

`/opt/minemeld/engine/current/bin/pip install arrow==0.14.2`
