### ISSUE TITLE
Exception handling domains in minemeld.ft.taxii.DataFeed

### ISSUE THREAD

**Issue by jtschichold** [PaloAltoNetworks/minemeld-core#50]
Exception handling domain indicators in taxii.DataFeed. Trace:

```
2016-09-12T17:09:19 (3329)amqp._callback ERROR: Exception in handling update on topic domainAggregator with params {u'source': u'domainAggregator', u'indicator': u'bestinghana.com', u'value': {u'confidence': 70, u'share_level': u'red', u'sources': [u'autofocusMMDemoEL'], u'autofocus_label': u'mmdemo', u'first_seen': 1473370831665L, u'type': u'domain', u'last_seen': 1473370831665L}}
Traceback (most recent call last):
  File "/opt/minemeld/engine/0.9.20/local/lib/python2.7/site-packages/minemeld/comm/amqp.py", line 344, in _callback
    m(**params)
  File "/opt/minemeld/engine/0.9.20/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 122, in _counter
    f(self, *args, **kwargs)
  File "/opt/minemeld/engine/0.9.20/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 453, in update
    value=fltvalue
  File "/opt/minemeld/engine/0.9.20/local/lib/python2.7/site-packages/minemeld/ft/base.py", line 122, in _counter
    f(self, *args, **kwargs)
  File "/opt/minemeld/engine/0.9.20/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 838, in filtered_update
    self._add_indicator(now, id_, indicator, value)
  File "/opt/minemeld/engine/0.9.20/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 777, in _add_indicator
    type_mapper['mapper'](oid, indicator, value)
  File "/opt/minemeld/engine/0.9.20/local/lib/python2.7/site-packages/minemeld/ft/taxii.py", line 608, in _stix_domain_observable
    type_="FQDN"
TypeError: __init__() got an unexpected keyword argument 'type_'
```

**Comment by jtschichold** [comment]
Fixed
